version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
      args:
        NODE_ENV: development
    ports:
      - "8111:8111"
    env_file:
      - .env
    restart: always
    depends_on:
      - opa
      - rabbitmq
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  opa:
    image: openpolicyagent/opa:0.45.0
    restart: on-failure
    volumes:
      - ./test/testFlows/policies/:/data
    command: run --server --log-level=debug --log-format=json-pretty --watch /data/policy.rego
    ports:
      - 8181:8181